#For Docker and Prod server
server:
  port: 8181
management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://strava-db/strava_db
    driver-class-name: org.postgresql.Driver
    username: ${STRAVA_DB_USERNAME}
    password: ${STRAVA_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: DETECT

telegram:
  bot:
    token: ${STRAVA_TELEGRAM_BOT_TOKEN}
    name: ${STRAVA_TELEGRAM_BOT_NAME}
    reconnectTimeout: 10000
    adminId: ${STRAVA_TELEGRAM_ADMIN_ID}

strava:
  client:
    id: ${STRAVA_CLIENT_ID}
    secret: ${STRAVA_CLIENT_SECRET}

logging:
  level:
    root: INFO
    com.dp_ua: INFO

  file:
    name: ./logs/file.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
