#For local test in IDE
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: ${TEST_DB_USERNAME}
    password: ${TEST_DB_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  output:
    ansi:
      enabled: DETECT
  mustache:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

telegram:
  bot:
    token: ${TEST_TELEGRAM_BOT_TOKEN}
    name: ${TEST_TELEGRAM_BOT_NAME}
    reconnectTimeout: 10000
    adminId: ${TEST_TELEGRAM_ADMIN_ID}

strava:
  client:
    id: ${STRAVA_CLIENT_ID}
    secret: ${STRAVA_CLIENT_SECRET}
  redirectionUrl: "http://localhost:8080/strava/redirect?chatId={chatId}"

logging:
  level:
    root: INFO
    com.dp_ua: DEBUG
    org.springframework.web: DEBUG

  file:
    name: ./logs/file.log
  pattern:
    #    just msg
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
